#!/usr/bin/env bash

: "${IOMMUT_TESTS_DIRECTORY:="@IOMMUT_INSTALL_DIR@/tests"}"

if ! command -v pytest >/dev/null; then
  echo "pytest is not installed"
  exit 1
fi

pytest "${IOMMUT_TESTS_DIRECTORY}"

